import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import IndustrialStore from './IndustrialStore';
import ExperienceLayer from './ExperienceLayer';
import SiteEnhancements from './SiteEnhancements';
import './showcase.css';
import './store.css';
import './premium.css';
import './light-premium.css';
import './app-shell.css';
import './site-enhancements.css';
import './a11y.css';
import './experience.css';

const IndustrialScene = lazy(() => import('./IndustrialScene'));

const COMPANY='UJJWAL ELECTRICAL AND MECHANICAL ENGINEERS ENTERPRISE';
const EMAIL='ujjwalelectricalengineers@gmail.com';
const machines=['HYUNDAI WIA','MAKINO','DAEWOO','BFW','DOOSAN'];
const services=[
 ['01','CNC SERVICE & MAINTENANCE','CNC equipment support, troubleshooting, preventive maintenance and machine-health assistance.'],
 ['02','INDUSTRIAL ELECTRICAL','Electrical engineering support for industrial environments, upgrades, controls and maintenance execution.'],
 ['03','MECHANICAL ENGINEERING','Mechanical repair, installation and engineering support with a practical focus on precision and reliability.'],
 ['04','PLANT INSTALLATION','Installation, maintenance and project execution support from planning through commissioning.'],
 ['05','SPINDLE & TOOLING SUPPORT','Practical support around spindle systems, holders, collets, rotating centres and machine tooling.'],
 ['06','BREAKDOWN RESPONSE','Structured troubleshooting aimed at identifying the actual operating problem and restoring dependable production.'],
] as const;
const SceneFallback=()=> <div className="scene-loading" aria-hidden="true"/>;
function Header({page,menu,setMenu}:{page:string;menu:boolean;setMenu:(open:boolean)=>void}){return <header className="site-light-nav"><a className="site-light-brand" href="#home" aria-label={COMPANY} onClick={()=>setMenu(false)}><span>UE</span><b>{COMPANY}</b></a><button className="site-light-menu" aria-expanded={menu} aria-label="Open navigation" onClick={()=>setMenu(!menu)}>{menu?'CLOSE':'MENU'}</button><nav className={menu?'site-light-links open':'site-light-links'} aria-label="Primary navigation"><a className={page==='home'?'active':''} aria-current={page==='home'?'page':undefined} href="#home" onClick={()=>setMenu(false)}>HOME</a><a className={page==='services'?'active':''} aria-current={page==='services'?'page':undefined} href="#services" onClick={()=>setMenu(false)}>SERVICES</a><a className={page==='shop'?'active shop-link':'shop-link'} aria-current={page==='shop'?'page':undefined} href="#shop" onClick={()=>setMenu(false)}>SHOP</a><a href="#services" onClick={()=>{setMenu(false);window.location.hash='services';setTimeout(()=>document.getElementById('premium-contact')?.scrollIntoView({behavior:'smooth'}),50)}}>CONTACT</a></nav><a className="site-light-cta" href={`mailto:${EMAIL}`}>START A PROJECT ↗</a></header>}
function HomePage(){return <div className="route-page home-route"><section className="home-hero-light"><div className="home-copy-light"><span className="eyebrow-light">{COMPANY} / INDUSTRIAL ENGINEERING</span><h1 className="kinetic-heading">Precision that <em>keeps industry moving.</em></h1><p>{COMPANY} supports CNC equipment, industrial systems, tooling and maintenance requirements with practical engineering execution.</p><div className="home-actions-light"><a className="button-black smart-focus" href="#shop">Explore tooling <b>→</b></a><a className="button-outline smart-focus" href="#services">Our services</a></div><div className="home-facts-light"><span>GSTIN <b>09CWDPD3387A1ZS</b></span><span>IEC <b>CWDPD3387A</b></span><span>GHAZIABAD / INDIA</span></div></div><div className="home-visual-light parallax-item" data-parallax="0.08"><div className="visual-ring ring-a"/><div className="visual-ring ring-b"/><div className="visual-card-light glass-panel"><img src="/hero-bearing-6200.svg" alt="6200 deep groove ball bearing" fetchPriority="high"/><span>FEATURED BEARING / 6200 DEEP GROOVE</span></div><div className="visual-tag tag-one">BALL BEARINGS</div><div className="visual-tag tag-two">CNC / VMC</div></div></section><section className="light-section-intro"><div><span className="section-code">01 / THE COMPANY</span><h2 className="kinetic-heading">Engineering for the <em>machine shop.</em></h2></div><p>From CNC service and industrial maintenance to rolling bearings, rotating centres and precision tooling, the experience is built around what buyers and plant teams actually need.</p></section><section className="home-cards-light bento-shell"><article className="bento-wide glass-panel"><small>01</small><h3>CNC &amp; VMC</h3><p>Tool holders, collets, pull studs, boring heads, workholding and practical machine support.</p><a href="#shop">Browse tooling →</a></article><article className="glass-panel bento-tall"><small>02</small><h3>Bearings</h3><p>Multi-brand ball bearings including open, shielded, sealed and clearance variants for machine-shop and industrial applications.</p><a href="#shop">Browse bearings →</a></article><article className="glass-panel"><small>03</small><h3>Built to enquire</h3><p>Add parts to your cart, choose quantities and send one clear enquiry when your list is ready.</p><a href="#shop">Open the shop →</a></article></section><section className="machine-rail-light"><div><span>SUPPORTED MACHINE EXPERIENCE</span><strong>Precision equipment</strong></div><div>{machines.map(machine=><span key={machine}>{machine}</span>)}</div></section><SiteEnhancements/></div>}
function ServicesPage(){return <div className="route-page services-route"><section className="services-hero-light"><span className="section-code">01 / SERVICES</span><h1 className="kinetic-heading">Industrial support.<br/><em>Done properly.</em></h1><p>Practical engineering support for CNC equipment, industrial electrical systems, mechanical assemblies and plant environments.</p></section><section className="services-list-light">{services.map(([no,title,copy])=><article key={no} className="service-line-light glass-panel"><span>{no}</span><div><h2>{title}</h2><p>{copy}</p></div><b>{title.split(' ')[0]}</b></article>)}</section><section className="service-bottom-light"><div className="service-dark-card"><span className="section-code">WHY UJJWAL</span><h3>Machine-first thinking.</h3><p>Understand the operating condition, identify the real fault, execute the work cleanly and leave a maintainable result.</p><div className="service-stats-light"><div><b>06</b><span>CORE SERVICES</span></div><div><b>05</b><span>MACHINE BRANDS</span></div><div><b>01</b><span>DIRECT CONTACT</span></div></div></div><div id="contact-panel" className="service-contact-card glass-panel"><span className="section-code">09 / CONTACT</span><h3>Need an engineer?</h3><a href="tel:+919971276078">+91 99712 76078</a><a href="tel:+919910228978">+91 99102 28978</a><a href={`mailto:${EMAIL}`}>{EMAIL}</a></div></section><SiteEnhancements/></div>}
export default function App(){const [page,setPage]=useState(()=>window.location.hash.replace('#','')||'home');const [menu,setMenu]=useState(false);const validPage=useMemo(()=>['home','services','shop'].includes(page)?page:'home',[page]);useEffect(()=>{const onHash=()=>{const next=window.location.hash.replace('#','')||'home';setMenu(false);if(next==='products'){setPage('shop');setTimeout(()=>document.getElementById('products')?.scrollIntoView({behavior:'smooth'}),40);return}if(next==='contact-panel'){setPage('services');setTimeout(()=>document.getElementById('contact-panel')?.scrollIntoView({behavior:'smooth'}),40);return}setPage(['home','services','shop'].includes(next)?next:'home');window.scrollTo({top:0,behavior:'auto'})};window.addEventListener('hashchange',onHash);if(!window.location.hash)history.replaceState(null,'','#home');return()=>window.removeEventListener('hashchange',onHash)},[]);return <div className="light-site"><a className="skip-link" href="#main-content">Skip to main content</a><ExperienceLayer/>{validPage!=='shop'&&<Suspense fallback={<SceneFallback/>}><IndustrialScene/></Suspense>}<Header page={validPage} menu={menu} setMenu={setMenu}/><main id="main-content" className="site-main-light">{validPage==='home'&&<HomePage/>}{validPage==='services'&&<ServicesPage/>}{validPage==='shop'&&<IndustrialStore/>}</main><footer className="site-light-footer"><span>© {new Date().getFullYear()} {COMPANY}</span><span>SECTOR-9 • SIDDHARTH VIHAR • GHAZIABAD • INDIA</span></footer></div>}
